apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: noc
rules:
  - apiGroups:
      - ''
    resources:
      - services/proxy
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
