apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-data
spec:
  storageClassName: redis-data
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce 
  persistentVolumeReclaimPolicy: Retain
  local:
    path: /mnt/kubernetes/redis/data
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/os
            operator: In
            values:
              - linux
          - key: node-role.kubernetes.io/worker
            operator: In
            values:
              - worker
          - key: type
            operator: In
            values:
              - on-premise
          - key: provider
            operator: In
            values:
              - host
          - key: service
            operator: In
            values:
              - virtualbox
          - key: region
            operator: In
            values:
              - local
          - key: availability_zone
            operator: In
            values:
              - local-c
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-log
spec:
  storageClassName: redis-log
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce 
  persistentVolumeReclaimPolicy: Retain
  local:
    path: /mnt/kubernetes/redis/log
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/os
            operator: In
            values:
              - linux
          - key: node-role.kubernetes.io/worker
            operator: In
            values:
              - worker
          - key: type
            operator: In
            values:
              - on-premise
          - key: provider
            operator: In
            values:
              - host
          - key: service
            operator: In
            values:
              - virtualbox
          - key: region
            operator: In
            values:
              - local
          - key: availability_zone
            operator: In
            values:
              - local-c
